version: 2.1

commands:
  restore_yarn_cache:
    parameters:
      path:
        type: string
    steps:
      - restore_cache:
          key: yarn-packages-<< parameters.path >>-v1.0-{{ checksum "<< parameters.path >>/yarn.lock" }}
  save_yarn_cache:
    parameters:
      path:
        type: string
    steps:
      - save_cache:
          key: yarn-packages-<< parameters.path >>-v1.0-{{ checksum "<< parameters.path >>/yarn.lock" }}
          paths:
            - << parameters.path >>/node_modules

jobs:
  build:
    docker:
      - image: circleci/node:14.15.3
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - restore_yarn_cache:
          path: .
      - restore_yarn_cache:
          path: subproject1
      - run:
          name: inspect cache
          command: ls -lad node_modules subproject1/node_modules || true
      - run:
          name: yarn install
          command: yarn install
      - save_yarn_cache:
          path: .
      - save_yarn_cache:
          path: subproject1
