version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.15.3
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - run:
          name: yarn install
          command: yarn install
      - save_cache:
          key: yarn-packages-v1.0-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
